### PR TITLE
Improve lists(sub-lists, term)

### PR DESCRIPTION
**Pull request by IdkGoodName**
Adds support for `<term>` tag and allows the creation of sub-lists. Em-dash(`—`) is used to separate the term and the description. If either of them is not present, em dash is not added.

---

```xml
<list type="number">
    <item>
        <term>A</term>
        <description>B</description>
    </item>
    <list type="bullet">
        <item><term>C</term></item>
        <item><description>D</description></item>
    </list>
    <item>E</item>
</list>
```
Outputs:
```md
1. A — B
   - C
   - D
2. E
```
> 1. A — B
>    - C
>    - D
> 2. E

### CODE REVIEW

**Comment by IdkGoodName** [comment]
Should I even update this PR?

**Comment by Doraku** [comment]
Yes fell free to do it, I am done with the big refactoring and just need to add xml comments to the Api library before the next version so there shouldn't be any big conflicts from now on.

**Comment by IdkGoodName** [comment]
Sorry for basically stretching this out for a month.

**Comment by Doraku** [comment]
oh no it's me who kept making big changes with all kind of conflicts haha

**Comment by IdkGoodName** [comment]
Is it ready for merge or what does need to be changed?

**Comment by Doraku** [comment]
not sure why there's some conflict, I will try to merge it manually (sorry wasn't really available in the past weeks).

**Comment by Doraku** [comment]
Finally got around to merge it. I hope it's ok for you after rereading the [microsoft documentation for list](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#list) I changed a little the implementation for table (`listheader` should only contains `term`s and `item`s only `description`s).

**Pull request merged**
